[project]
name = "fast-mcp"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27,<0.4.0",
    "langchain-openai>=0.3.35,<0.4.0",
    "mcp-use>=1.3.10,<2.0.0",
    "pydantic[email]>=2.11.7,<3.0.0",
]

[tool.uv]
package = false